//
//  GamesManager.swift
//  NetflixClone
//
//  Created by Abhishek Tyagi on 28/01/24.
//

import Foundation

protocol GamesManagerDelegate {
    func getWinterSelection() async throws -> [GamesModel]
    func getExclusiveGames() async throws -> [GamesModel]
    func getNonoGames() async throws -> [GamesModel]
    func getBrainTeaser() async throws -> [GamesModel]
    func getHotGames() async throws -> [GamesModel]
}

final class GamesManager: GamesManagerDelegate {

    func getWinterSelection() async -> [GamesModel] {
        return [
            GamesModel(name: "CHRISTMAS MAZE MANIA", descrip: "Begin a festive journey in our Christmas maze game! Guide Santa using your mouse, touch, or keyboard through captivating mazes to bring joy to waiting children. Find optimal paths, deliver heartwarming gifts, and immerse yourself in holiday spirit across 15 challenging levels. Spread Christmas cheer in this enchanting game!", image: "christmasMaze", url: "https://html5.gamedistribution.com/fd8440d9ed374f06b745cb299cb61819/?gd_sdk_referrer_url=https://gamedistribution.com/games/christmas-maze-mania"),
            GamesModel(name: "XMAS MAHJONG TRIO SOLITAIRE", descrip: "Embark on a festive adventure with 'Xmas Mahjong Trio Solitaire.' Arrange Mahjong tiles in a horizontal stack of 9, strategically making trios disappear for extra cheer. Be cautious of overflowing stacks, as it signals the end of the game. Unwrap the joy of Xmas in this simple yet engaging holiday experience!", image: "xMasMahjong", url: "https://html5.gamedistribution.com/f91beee6fad943098b0fc3f88e1f1019/?gd_sdk_referrer_url=https://gamedistribution.com/games/xmas-mahjong-trio-solitaire"),
            GamesModel(name: "SKI KING 2024", descrip: "Your favorite slopes have finally opened. So don't hesitate and run down the slope, collect the coins, improve your skills and become the king of skiing. Can you also escape the avalanche?", image: "skiKing", url: "https://html5.gamedistribution.com/f27ca832c25944d49509cc9c5429689a/?gd_sdk_referrer_url=https://gamedistribution.com/games/ski-king-2024"),
            GamesModel(name: "SNOWBOARD HERO", descrip: "Snowboard your way down the mountain, while avoiding the obstacles. Don't crash! Features: - Interactive tutorial. Anyone can play this game! - Fast, pumping music suitable for X sports. - Beautiful winter christmas landscape. - Collect banners to earn extra points. - Fans of winter skifree xmas or snowboarding will love this game.", image: "snowboardHero", url: "https://html5.gamedistribution.com/716194ae04b34da6830eff3043d2af87/?gd_sdk_referrer_url=https://gamedistribution.com/games/snowboard-hero"),
            GamesModel(name: "CHRISTMAS MEMORY", descrip: "Click the cards to flip a christmas items. Memorize their position and match them up in pairs. Match all of the cards on the board to complete the level. Each level with a difference symbol and it's harder than the last and you have limited time to complete them. It's time to check your memory skill now. What's the max level can you play?", image: "christmasMemory", url: "https://html5.gamedistribution.com/cc5cf906e19f4bba96daa51b5aee7864/?gd_sdk_referrer_url=https://gamedistribution.com/games/christmas-memory-3"),
        ]
    }
    
    func getExclusiveGames() async throws -> [GamesModel] {
        return [
            GamesModel(name: "BUILD YOUR AQUARIUM", descrip: "Build Your Aquarium is a popular Sea World fishing game for players! You run an aquarium with customers with different needs. You need to keep going to the bottom of the sea to fish, collect all kinds of fish, unlock new tanks, expand your operation and your customers will grow! Become the richest aquarium tycoon! Join us now!", image: "buildYourAquarium", url: "https://html5.gamedistribution.com/55eaa28d7a6343f8951b8709aae7145d/?gd_sdk_referrer_url=https://gamedistribution.com/games/build-your-aquarium"),
            GamesModel(name: "MYSTIC MAHJONGG", descrip: "Embark on a captivating journey into the world of Mystic Mahjongg! Solve challenging puzzles by matching pairs of themed tiles adorned with intricate symbols! Сhallenge yourself with increasingly difficult levels, create a unique atmosphere by choosing new avatars and backgrounds. Immerse yourself in the magical world of Mystic Mahjongg - a new relaxing game with stunning visuals - explore all levels and uncover the magic hidden within the tiles! Begin your journey today with Mystic Mahjongg!", image: "mysticMahjongg", url: "https://html5.gamedistribution.com/fdedbc8bb114409b84e1d1ff853291ee/?gd_sdk_referrer_url=https://gamedistribution.com/games/mystic-mahjongg"),
            GamesModel(name: "FREE THE BALL", descrip: "Try out Free the Ball, a super fun puzzle game! Your job is to guide the ball to its goal by moving blocks around. And get this – there are a whopping three thousand levels to play, and they're all free! No need to buy anything.", image: "freetheBall", url: "https://html5.gamedistribution.com/f7364610976f43d1b31f730d9995641a/?gd_sdk_referrer_url=https://gamedistribution.com/games/free-the-ball-1"),
            GamesModel(name: "HIGH SPEED CRAZY BIKE", descrip: "Get ready to take on the ultimate mud dirt bike racing challenge as you barrel through rough terrain at breakneck speeds, using your skills and quick reflexes to navigate through a myriad of obstacles and emerge victorious in this adrenaline-fueled test of skill and daring.", image: "highBike", url: "https://html5.gamedistribution.com/e804dc59653849d5b24fa5919662c2af/?gd_sdk_referrer_url=https://gamedistribution.com/games/high-speed-bike-simulator"),
            GamesModel(name: "BIKE STUNT RACE MASTER 3D RACING", descrip: "In this bike game Tracks are arranged according to real bike race scenarios which carry multiple levels from easy trials to technical approach. Are you motorcycle racer?? Let’s ﬁnd out what you have, use your motorcycle driving tricks and ﬁnish all the challenging task.", image: "bikeStuntRacing", url: "https://html5.gamedistribution.com/a81c87f3a54f436eb152eb8654a6b254/?gd_sdk_referrer_url=https://gamedistribution.com/games/bike-stunt-race-master-3d-racing-1"),
        ]
    }
    
    func getNonoGames() async throws -> [GamesModel] {
        return [
            GamesModel(name: "FOR HONOR WARRIORS IO", descrip: "Fight your way to becoming the greates warrior of all time! Engage in a merciless free-for-all-war, Grow and fight with huge weapons, and unlock 12 FOR HONOR heroes! Fight endlessly and defeat hords of other players to become the strongest warrior ever. One hit Kills...stay focused!", image: "forHonorWarriors", url: "https://html5.gamedistribution.com/c23c547669904e348202fbba7f5f8306/?gd_sdk_referrer_url=https://gamedistribution.com/games/for-honor-warriors-io"),
            GamesModel(name: "BUBBLES & HUNGRY DRAGON", descrip: "Join a hilarious battle of dragons! ​Pick-up your mighty dragon and burst as many bubbles as possible! ​Aim, shoot and match bubbles of the same color to defeat other players in classic arcade team matches!​​", image: "bubblesHungryDragon", url: "https://html5.gamedistribution.com/136ce9a952c54adf93ef9dbfcc663904/?gd_sdk_referrer_url=https://gamedistribution.com/games/bubbles-and-hungry-dragon"),
            GamesModel(name: "TOM CLANCY'S SHOOTOUT", descrip: "Enter the most intense Training Ground! Show your mastery of weapons by shooting targets with reflex and precision. Shoot the drones before other players to unlock better weapons. Select an elite operator and get the world's best score!", image: "tomClancy", url: "https://html5.gamedistribution.com/6ebe84c1df814143978118cf948329ce/?gd_sdk_referrer_url=https://gamedistribution.com/games/tom-clancy's-shootout"),
            GamesModel(name: "RABBIDS VOLCANO PANIC", descrip: "Play Rabbids Volcano Panic on nano.ubisoft.com. Let us know what do you think about the game in the comments Rabbids island is crumbling in a colossal volcanic eruption! Stay safe as long as you can and make your way on the collapsing floor before the other panicking Rabbids take you down with them! Pick-up bonus items and trap other players to play dirty and make them fall first!", image: "rabbidsVolcano", url: "https://html5.gamedistribution.com/c8608aa5e1ee4f61967844ba20a279e9/?gd_sdk_referrer_url=https://gamedistribution.com/games/rabbids-volcano-panic"),
            GamesModel(name: "ASSASSIN'S CREED FREERUNNERS", descrip: "Try Assassin's Creed Freerunners on nano.ubisoft.com. It’s the ultimate Assassin freerunning test! Appoint your most trusted Assassin and enter the animus with 7 other players, surpass the dangers and get to the extraction point first! Climb on roofs, jump on walls, use the environment and take an epic leap of faith to increase your synchronization and summon legendary characters from the entire Assassin’s Creed series. Initiating simulation…3…2…1..Run!", image: "assassinCreed", url: "https://html5.gamedistribution.com/b5e69d9778554b0e9cb0a6d5d6a0e43d/?gd_sdk_referrer_url=https://gamedistribution.com/games/assassin's-creed-freerunners"),
        ]
    }
    
    func getBrainTeaser() async throws -> [GamesModel] {
        return [
            GamesModel(name: "WORD SEARCH", descrip: "Word Search is one of the best word games to exercise your brain, vocabulary as well as pattern recognition. The goal of Word Search is to find all the words that are listed next to the puzzle grid. The words are hidden inside the puzzle grid and go in all directions: horizontal, vertical, diagonal as well as backwards. Go to the calendar to find more puzzles. Come back every day for at least a few minutes to exercise your mind and the brain!", image: "wordSearch", url: "https://html5.gamedistribution.com/c13ee9c06edc4f0a8d7f6f291a7c13d8/?gd_sdk_referrer_url=https://gamedistribution.com/games/word-search-2"),
            GamesModel(name: "WORDS OF WONDERS", descrip: "With a lot of levels to solve, each with a unique set of letters to connect, you'll never run out of brain-teasing fun. But don't worry if you get stuck, you can always use hints to reveal random letters or hammer power-ups to reveal a letter of your choosing. As you progress through the levels, you'll also have the chance to collect different pictures of the world wonders.", image: "wordsOfWonders", url: "https://html5.gamedistribution.com/c8ba1cb2f23d40b5a19fd606fcc3e50b/?gd_sdk_referrer_url=https://gamedistribution.com/games/words-of-wonders"),
            GamesModel(name: "KITTY SCRAMBLE", descrip: "Help cute kitty to find hidden words - discover them on the board with letters. Use hints, search the words on the board, and swipe through them to open! Invite your friends and play together.", image: "kittyScramble", url: "https://html5.gamedistribution.com/944186abe50e452dac7f0e8d3e0a8814/?gd_sdk_referrer_url=https://gamedistribution.com/games/kitty-scramble"),
            GamesModel(name: "DAILY SUDOKU", descrip: "Daily Sudoku provides a thought-provoking journey that will keep you engrossed until every puzzle box is filled. If you enjoy challenging your intellect and sharpening your problem-solving skills, then you've come to the perfect spot.", image: "dailySudoku", url: "https://html5.gamedistribution.com/dd9701cd84da40699cdc404645f29c1f/?gd_sdk_referrer_url=https://gamedistribution.com/games/daily-sudoku-2"),
            GamesModel(name: "HEXA LOOP 3D", descrip: "Relaxing Puzzle game. People love it! with more than 100Levels ∞ Hexa Loop 3D is a fun way of increasing your logic skills. It can be considered a puzzle game about creating intricate looping patterns or just the application of using a simple concept: connecting multiple things and making fun of it. If you are looking for stress relief or a relaxing game type, enjoy the loop!", image: "hexaloop", url: "https://html5.gamedistribution.com/e5761671aa0e4d2eac325d75f251717e/?gd_sdk_referrer_url=https://gamedistribution.com/games/hexa-loop-3d"),
        ]
    }
    
    func getHotGames() async throws -> [GamesModel] {
        return [
            GamesModel(name: "MR BEAN JUMP", descrip: "Jump on moving blocks and get as high as you can in the new official Mr Bean game! Unlock hilarious costumes and hats from the show to make Mr Bean as unique as you like. Unlock fun backgrounds and new blocks from the hit animated show.", image: "mrBeanJump", url: "https://html5.gamedistribution.com/21e669394e34431197b6689fd8f9b064/?gd_sdk_referrer_url=https://gamedistribution.com/games/mr-bean-jump"),
            GamesModel(name: "HIPPO SUPERMARKET", descrip: "Meet Jack Ma, a cute hippo who dreams of opening his own supermarket. But he doesn't know how to do it. He needs your help to make his dream come true.In this fun and addictive game, you need to merge the same items to get higher-level items, and then sell them to earn money. The more money you make, the more you can help Jack Ma build his store.", image: "hippoSupermarket", url: "https://html5.gamedistribution.com/9d6eebd716f748b4b0aee43a788f06b0/?gd_sdk_referrer_url=https://gamedistribution.com/games/hippo-supermarkete"),
            GamesModel(name: "SNIPER SHOOTER 2", descrip: "Aim and Shoot! Kill the bad guys and accomplish missions to become the master hitman. Just turn your device to aim and TAP TO SHOOT and kill", image: "sniperShooter", url: "https://html5.gamedistribution.com/9c744a2dfb4b43e588b50db10999ed8e/?gd_sdk_referrer_url=https://gamedistribution.com/games/sniper-shooter-2"),
            GamesModel(name: "WORMSARENA.IO", descrip: "A great Snake IO game is beginning with the Worms Arena IO game! The baits are all around the map and collect them to make your snake the largest of the arena. Make strategic moves and trap your opponents to make them fail. Try to achieve the highest score and wear the crown. Unlock new snakes at the marketplace with coins. Let the super snake adventure begin!", image: "wormsArenaIo", url: "https://html5.gamedistribution.com/de5f668c21a7489ebc62f932efb75f78/?gd_sdk_referrer_url=https://gamedistribution.com/games/wormsarena.io"),
            GamesModel(name: "MONEY MOVERS 1", descrip: "These two criminals need your help to escape this heavily guard prison. Steal as much money as you can and don't get caught by the security. Good luck playing Money Movers !", image: "moneyMovers", url: "https://html5.gamedistribution.com/c035e676ef654227b1537dabbf194e00/?gd_sdk_referrer_url=https://gamedistribution.com/games/money-movers-1"),
        ]
    }
    
}
